---
- name: Delete` users by passing vars to playbook with awx
  hosts:  all
  tasks:
    - name: "delete {{ username }} in {{ homedir }}"
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        comment: "{{ username }} is paździerz"
        shell: /bin/bash
        home: "{{ homedir }}"
        uid: 6666
