---
- name: first playbook test
  hosts: all
  tasks:
    - name: Get uptime from server
      ansible.builtin.command: uptime
      register: serveruptime
    - name: display uptime
      ansible.builtin.debug:
        msg: '{{ serveruptime }}'
